apiVersion: v1
kind: ConfigMap
metadata: 
  name: config
data:
  MYSQL_DATABASE: bankappdb
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root
