name: Streamlined CI/CD for Deploying Banking Application
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile with Maven
        run: mvn compile

  security-check:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy
        run: | # installation script
          ...
      - name: Trivy FS Scan
        run: trivy fs --format json --output trivy_report.json .
      - name: Install Gitleaks
        run: sudo apt-get install -y gitleaks
      - name: Run Gitleaks Scan
        run: gitleaks detect --source . --report-path=gitleaks-report.json --report-format=json

  test:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Unit Tests
        run: mvn test

  build-and-sonarqube-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn package
        name: Build JAR
      - uses: actions/upload-artifact@v4
        name: Upload JAR Artifact
        with: { name: app-jar, path: target/*.jar }
      - uses: SonarSource/sonarqube-scan-action@v4.1.0
        name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        with: { pollingTimeoutSec: 600 }
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      - uses: docker/build-push-action@v6
        name: Build and Push Docker Image
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: radhagowthamhub/bankapp:${{ github.run_number }}
      - name: Update image tag in Kubernetes manifest
        run: |
          sed -i "s|radhagowthamhub/bankapp:.*|radhagowthamhub/bankapp:${{ github.run_number }}|g" manifest/ds.yml
      - name: Commit and Push Updated Manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifest/ds.yml
          git commit -m "Update image tag to build ${{ github.run_number }}"
          git push origin main
