name: streamlined cicd for deploying banking application
on:
  push:
# pull request:
    branches: [main]
jobs: # similar like pipeline
  compile: # similar like stage
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven
    - name: Build with Maven
      run: mvn compile
  security-check:
    runs-on: self-hosted
# note: here all the stages will get run in one go, but i want to run after other, using "needs"
    needs: compile
    # now onece the compile is completed then security-check will get executed
    steps:
# it get the code into runner enviroment and allow you to build/test/run scripts or any operation that requires to acces source code    
    - name: Checkout code 
      uses: actions/checkout@v4
    
    - name: trivy installation
      run: |
       sudo apt-get install wget apt-transport-https gnupg lsb-release
       wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
       echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y
     
    - name: trivy FS scan
      run: trivy fs --format table -o trivy_report.json .
      
    - name: gitleak installation
      run: sudo apt install gitleaks -y
    - name: Gitleaks Code Scan  
      run: gitleaks detect source . -r gitleaks-report.json -f json
  test:
    runs-on: self-hosted
    needs: security-check
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: unit test
      run: mvn test
  build:
    runs-on: self-hosted
    needs: test
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: build
      run: mvn package
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: radhagowthamhub/bankapp:latest
        file: ./Dockerfile   
